### ISSUE TITLE
Scene rendering is broken

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/PyChaste#1]
**Describe the bug**
See [PyChaste/issues/5](https://github.com/jmsgrogan/PyChaste/issues/5): 

> Returning a VTK Renderer to Python is broken, causing failures in tutorials and breaking of rendering in Jupyter notebook.s

**To Reproduce**
[Build and install PyChaste from source](https://github.com/jmsgrogan/PyChaste#install-from-source-linux-only) with `VTK ==7.1.1`, which is the oldest available version on Ubuntu 22.04.

In a Jupyter notebook:
```
import chaste 
chaste.init()
from chaste.visualization import JupyterNotebookManager, VtkScene2

scene = VtkScene2()
nbManager = JupyterNotebookManager()
nbManager.vtk_show(scene)
```

**Error**
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: Unregistered type : vtkSmartPointer<vtkRenderer>

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 nbManager.vtk_show(scene)

File ~/Chaste/build/projects/PyChaste/python/chaste/visualization/fortests.py:134, in JupyterNotebookManager.vtk_show(self, scene, width, height, output_format, increment)
    132 renderWindow = vtk.vtkRenderWindow()
    133 renderWindow.SetOffScreenRendering(1)
--> 134 renderWindow.AddRenderer(scene.GetRenderer())
    135 renderWindow.SetSize(width, height)
    136 renderWindow.Render()

TypeError: Unable to convert function return value to a Python type! The signature was
	(self: chaste.visualization._chaste_project_PyChaste_visualization.VtkScene2) -> vtkSmartPointer<vtkRenderer>
```

**Comment by kwabenantim** [comment]
Interestingly, this bug exists for vtk 6.3.0 as well when compiling with [2019 PyChaste](https://github.com/jmsgrogan/PyChaste/commit/48a9863d2c941c71e47ecb72e917b477ba5c1413) and [2019 Chaste](https://github.com/Chaste/Chaste/tree/2019.1) on Ubuntu 18.04. Rebuilding an old vtk in #2 may not necessarily resolve the broken rendering.

**Comment by kwabenantim** [comment]
The last working version seems to be the one used in the [docker image](https://hub.docker.com/r/jmsgrogan/pychaste) from 2016 i.e. Pychaste [v3.4.2](https://github.com/jmsgrogan/PyChaste/releases/tag/v3.4.2) which uses Boost Python bindings. From [v3.4.3](https://github.com/jmsgrogan/PyChaste/releases/tag/v3.4.3), PyChaste was migrated to PyBind11.

**Comment by kwabenantim** [comment]
- PR #5 has fixed `TypeError: Unregistered type : vtkSmartPointer<vtkRenderer>`.
- Next step is getting animations to render correctly in the browser.

**Comment by MILeach** [comment]
After the merge of #5, animations can be displayed in the notebook, but there is a memory leak which quickly (in the order of 30 seconds - few minutes) crashes the host machine.

## Steps to Fix
- [x] Test equivalent simulation code outside of the notebook and with no visualisation to check the leak is not part of the simulation. *No leak present*
- [x] Check that halting the offending cell in the notebook pauses the memory leak. *Memory leak pauses when the cell is stopped*
- [x] Try running a single step simulation in the notebook and checking whether the leak continues - this will identify whether it is simulation code or an issue with the visualisation code. *Leak does not continue to occur for short simulations - these reach completion and memory usage stops increasing.*
- [x] Investigate visualistion code + JupyterSceneModifier2 for any obvious memory hogs, e.g saving every frame/instantiation every frame of something that might not get garbage collected.
  - [x] fortests.py:132 - new vtkRenderWindow created every frame
  - [x] fortests.py:146 - new vtkWindowToImageFilter created every frame
  - [x] fortests.py:150 - new vtkPNGWriter created every frame
  - [x] fortests.py:151 - SetWriteToMemory(1) - check if vtk clears these

## Fixed
The vtkRenderWindows being created each frame were not GC'd. Fixed by having a single render window as a class member of JupyterNotebookManager
